version: '3'

networks:
  laravel:
services:
  app:
    env_file:
      - ./src/.env
    build:
      context: ./dockers
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - php
      - redis
      - mysql
      - mailhog
    networks:
      - laravel

  mysql:
    env_file:
      - ./src/.env
    image: mariadb:10.6
    restart: unless-stopped
    tty: true
    ports:
      - "${DB_EXTERNAL_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER:  ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  php:
    env_file:
      - ./src/.env
    build:
      context: ./dockers
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "9001:9000"
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - laravel

  redis:
    env_file:
      - ./src/.env
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - laravel

  composer:
    build:
      context: ./dockers
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./src:/var/www/html
    depends_on:
      - app
      - php
    entrypoint: [  'composer', 'install', '--ignore-platform-reqs' ]
    networks:
      - laravel

  # npm:
  #   image: node:current-alpine
  #   volumes:
  #     - ./:/var/www/html
  #   ports:
  #     - "3000:3000"
  #     - "3001:3001"
  #     - "5173:5173"
  #   working_dir: /var/www/html
  #   entrypoint: [ 'npm' ]
  #   networks:
  #     - laravel

  artisan:
    build:
      context: ./dockers
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - composer
      - mysql
    entrypoint: [ 'php', '/var/www/html/artisan', 'migrate' ]
    networks:
      - laravel

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - laravel
